Add most populars
PavelSpectr/java-filmorate pull request #19
Opened 2023-07-24 12:34 UTC by evga2022

2023-07-24 13:29 UTC, Mishcore requested changes

2023-07-24 13:29 UTC, Mishcore commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    private Long id;
Думаю, хранить id режиссёров достаточно в int, их вряд ли наберётся больше 2-х миллиардов

2023-07-24 13:29 UTC, Mishcore commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +import java.util.*;
Импортирование пакета полностью, через *, обычно нежелательно

2023-07-24 13:29 UTC, Mishcore commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +            "COUNT(DISTINCT(film_likes.user_id)) AS likes_count " +
Ключевое словоDistinct, возможно, излишне, так как в БД уже стоит ограничение на уникальность значений

2023-07-24 13:29 UTC, Mishcore commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +            "COUNT(DISTINCT(film_likes.user_id)) AS likes_count " +
см. выше

2023-07-24 13:29 UTC, Mishcore commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorageImpl.java
> +import java.util.*;
см. выше

2023-07-24 13:29 UTC, Mishcore commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorageImpl.java
> +        film.setLikesCount(0);
Строка излишня, т.к. поле с типом int по умолчанию инициализируется со значением 0.

2023-07-24 13:33 UTC, evga2022 commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    private Long id;
Во всех остальных моделях мы используем Long для хранения идентификаторов, не думаю что есть причины для режиссеров делать исключение

2023-07-24 13:37 UTC, evga2022 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +            "COUNT(DISTINCT(film_likes.user_id)) AS likes_count " +
Оно тут не лишнее, без него показывается в два раза больше лайков чем с ним

2023-07-24 13:37 UTC, evga2022 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +            "COUNT(DISTINCT(film_likes.user_id)) AS likes_count " +
Оно тут не лишнее, без него показывается в два раза больше лайков чем с ним

2023-07-24 13:41 UTC, evga2022 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorageImpl.java
> +        film.setLikesCount(0);
Пожалуй мы можем полностью удалить InMemory реализацию хранилища

2023-07-24 13:45 UTC, evga2022 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorageImpl.java
> +import java.util.*;
Пожалуй мы можем полностью удалить InMemory реализацию хранилища

2023-07-24 13:56 UTC, kirinichny reviewed
Оставил комментарии, в основном по SQL запросам. В остальном всё круто :)

2023-07-24 13:56 UTC, kirinichny commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +import java.util.*;
Импорт через .* лучше не использовать

2023-07-24 13:56 UTC, kirinichny commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +    private static final String SELECT_POPULAR_FILMS_QUERY_1 = "SELECT " +
Из названия  SELECT_POPULAR_FILMS_QUERY_1 не понятно, что такое 1, и чем он отличается от 2.

2023-07-24 13:56 UTC, kirinichny commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +    private static final String SELECT_POPULAR_FILMS_QUERY_2 =
Название константы не соответствует запросу.

2023-07-24 13:56 UTC, kirinichny commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +    private static final String SELECT_POPULAR_FILMS_QUERY_YEAR =
смотри выше

2023-07-24 13:56 UTC, kirinichny commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +    private static final String SELECT_POPULAR_FILMS_QUERY_3 =
Оно же)

2023-07-24 13:56 UTC, kirinichny commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +    private boolean filmLikeExist(long filmId, long userId) {
Да это хорошо скажется на производительности. Но можно запрос немного доработать, тогда он еще будет быстрей. 

1. Добавить в SQL запрос limit 1, тем самым мы не будем заставлять базу выбирать все лайки, если хоть один лайк есть, значит лайки есть. 

2. нам нет необходимости выбирать поле  film_likes.film_id, можно просто написать так: SELECT 1 FROM. Далее просто проверяем, возвращает запрос единицу или нет.

2023-07-24 13:56 UTC, kirinichny commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +        } else {
Можно этот метод сделать красивей, если убрать из JOIN film_genres AS fg ON films.id = fg.film_id AND fg.genre_id = ?, fg.genre_id = ? вот эту часть в WHERE, а джоин перенести в общий запрос. То в методе getPopularFilms( можно будет только собрать строку для условия WHERE. И не потребуется разбивать большой запрос на кучу маленьких. 

Хотя это будет немного в ущерб производительности :)

2023-07-24 22:05 UTC, Mishcore approved these changes

2023-07-24 23:23 UTC, evga2022 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +    private static final String SELECT_POPULAR_FILMS_QUERY_1 = "SELECT " +
Это часть составного запроса, тут цифры указывают порядковый номер в котором конкатенируются строки

2023-07-24 23:25 UTC, evga2022 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +    private static final String SELECT_POPULAR_FILMS_QUERY_2 =
Это не целый запрос, это часть составного запроса, здесь та его часть что добавляет фильтр по жанру

2023-07-24 23:26 UTC, evga2022 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +    private static final String SELECT_POPULAR_FILMS_QUERY_YEAR =
как отписалась выше это не самостоятельный запрос, это часть составного, та что в обязательном порядке следует за первой

2023-07-24 23:27 UTC, evga2022 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +    private static final String SELECT_POPULAR_FILMS_QUERY_3 =
Это не целый запрос, это часть составного запроса, здесь та его часть что добавляет фильтр по годам)

2023-07-24 23:29 UTC, evga2022 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +    private boolean filmLikeExist(long filmId, long userId) {
1. У нас и так стоит ограничение по уникальности двух ключей, больше одного лайка мы так не выберем в любом случае.
2. Мне кажется это не должно повлиять на производительность

2023-07-24 23:42 UTC, evga2022 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +        } else {
Ты не понял почему я его разбила на составные части, здесь у меня два необязательных параметра, это жанр и год релиза фильма, если их нет то и передавать в запрос их не нужно.
 Жанр я вынесла в отдельный join для увеличения производительности (так запрос сразу возьмет только те фильмы что соответствуют по жанру, а не будет получившееся пересечение со всеми фильмами фильтровать в where). 
Так же следом за where частью следует часть с сортировкой результата и ограничением по количеству. 
Таким образом мы лишь сократим числа частей составного запроса с 4-х до 3-х, мне кажется жертвовать производительностью ради этого не имеет большого смысла

2023-07-24 23:58 UTC, kirinichny commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +    private static final String SELECT_POPULAR_FILMS_QUERY_1 = "SELECT " +
В константах желательно избегать цифр. Они не дают ни какой информации. Из подобных названий не понятно, что в них содержится. Лучше использовать названия из которых понятно их содержимое.

2023-07-25 09:38 UTC, kirinichny approved these changes

2023-07-25 10:03 UTC, merged