Add reviews
PavelSpectr/java-filmorate pull request #20
Opened 2023-07-24 14:01 UTC by KurochkinAndrew

2023-07-24 14:10 UTC, kirinichny commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public List<Review> getReviewsOfFilm(@RequestParam(defaultValue = "") Long filmId,
Название методу лучше дать getReviews, так как он может выводить отзывы без указания конкретного фильма.

2023-07-24 14:10 UTC, kirinichny commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/ReviewDbStorageImpl.java
> +    public Review addReview(Review review) {
Лучше добавить аннотацию Override, когда реализовываешь методы интерфейса.

2023-07-24 14:10 UTC, kirinichny commented on src/main/resources/schema.sql
> +drop table if exists review_likes cascade;
Это лучше убрать с кода, для тестов надо, но в рабочей программе не будут сохраняться данные, будут удаляться при каждом запуске программы.

2023-07-24 15:23 UTC, kirinichny approved these changes

2023-07-24 23:19 UTC, evga2022 requested changes

2023-07-24 23:19 UTC, evga2022 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public List<Review> getReviews(@RequestParam(defaultValue = "") Long filmId,
Здесь если filmId не обязательный параметр правильнее указать required = false

2023-07-25 13:06 UTC, evga2022 approved these changes

2023-07-26 11:04 UTC, merged