add-search (Михаил). Поиск
PavelSpectr/java-filmorate pull request #21
Opened 2023-07-25 02:54 UTC by Mishcore

Готово к слиянию. Содержит функционал Режиссёров

2023-07-25 09:59 UTC, evga2022 requested changes, later dismissed

2023-07-25 09:59 UTC, evga2022 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +    private static final String SELECT_FILM_BY_DIRECTOR_SORT_BY_LIKES_QUERY =
Я бы предложила не делать множество вариантов запроса WHERE с каждым сочетанием переданных параметров, а составить один WHERE исходя из тех параметров что были переданы

2023-07-25 10:31 UTC, PavelSpectr approved these changes

2023-07-25 12:09 UTC, Mishcore commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorageImpl.java
> +    private static final String SELECT_FILM_BY_DIRECTOR_SORT_BY_LIKES_QUERY =
Предлагаю отложить пока на попозже

2023-07-26 00:35 UTC, kirinichny approved these changes

2023-07-26 02:53 UTC, merged